dist: bionic
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

script:
  - echo "________TypeListErase___________Start_________"
  - cd HW1
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
  - ./TypeListErase
  - cd ../..
  - echo "________TypeListErase___________End___________"

notifications:
  email:
    recipients:
      - grib.a@phystech.edu
    on_success: change
    on_failure: always