dist: bionic
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

script:
  - echo "________HW________tests___________Start_________"
  - cd HW1and2
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
  - ./HW
  - cd ../..
  - echo "________HW________tests___________End___________"
  - echo "________Singleton_tests___________Start_________"
  - cd Singleton
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
  - ./Singleton
  - cd ../..
  - echo "________Singleton_tests___________End___________"

notifications:
  email:
    recipients:
      - grib.a@phystech.edu
    on_success: change
    on_failure: always
