dist: bionic
sudo: required

language: cpp

os:
  - linux

compiler:
  - gcc

script:
  - echo "________HW_tests___________Start_________"
  - cd HW1and2
  - mkdir cmake-build
  - cd cmake-build
  - cmake ../
  - make
  - ./HW
  - cd ../..
  - echo "________HW_tests___________End___________"

notifications:
  email:
    recipients:
      - grib.a@phystech.edu
    on_success: change
    on_failure: always

branches:
    only:
    - master
